# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7545e0362933a09952241d3461ddd342e5e834c80ee803c92ec71be82343dcc2a6f67e277c49aa59a123c8b09a97dec183eb556b0a098e0f7e6253b8351348b

test:
  secret_key_base: 041f777c74db26003b7075a4bcd6a54ee51c471de594cc5ca4259d7abdfcc697111de31409306076f3ed24882d51fd470da49ebeab7a65965cb0554ce99497b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
